### ISSUE TITLE
Cannot find module 'parcel-bundler/src/assets/HTMLAsset'

### ISSUE THREAD

**Issue by moos** [stoically/parcel-plugin-html-externals#1]
```
Error: Cannot find module 'parcel-bundler/src/assets/HTMLAsset'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
 ...
```
Version 0.1.2.
```
$ npx parcel -V
1.12.4
```

**Comment by stoically** [comment]
Current workaround: install `parcel-bundler` instead of `parcel`

**Comment by JoshuaHintze** [comment]
Seeing this issue too. Installing the extra dependency works however. Just a note. I am using parcel globally installed.

**Comment by hxse** [comment]
@stoically 
When i use  parcel-bundler globally installed, I made the same mistake.
Is there a solution?

**Comment by stoically** [comment]
Installing `parcel-bundler` as package dependency should work

**Comment by hxse** [comment]
> Installing `parcel-bundler` as package dependency should work

`NODE_PATH` `C:\Users\username\AppData\Local\Yarn\Data\global\node_modules`
`PATH` `C:\Users\username\AppData\Local\Yarn\Data\global`
Setting environment variables and restarting the terminal, solve the problem.
Beacuse, the global path cannot be found by require().

**Comment by trapcodeio** [comment]
Just Encountered this issue, installing parcel-bundler worked for me.
